<?php

// Language definitions used in admin_index.php
$lang_admin_index = array(

'fopen disabled message'			=>	'Imposible comprobar si hay actualizaciones, ya que \'allow_url_fopen\' está deshabilitado en el sistema.',
'Upgrade check failed message'		=>	'La comprobación de actualizaciones falló por razones desconocidas.',
'Running latest version message'	=>	'Estás utilizando la versión más reciente de FluxBB.',
'New version available message'		=>	'Una nueva versión de FluxBB ha sido lanzada. Puedes descargas la versión más reciente en %s.',
'Not available'						=>	'No disponible',
'Forum admin head'					=>	'Administración del foro',
'NA'								=>	'no disponible',
'Welcome to admin'					=>	'Bienvenido al panel de administración de FluxBB. Desde aquí puedes controlar aspectos vitales del foro. Dependiendo de si eres un administrados o moderador, puedes:',
'Welcome 1'							=>	'Organizar categorías y foros.',
'Welcome 2'							=>	'Establecer las opciones y preferencias generales del foro.',
'Welcome 3'							=>	'Controlar permisos para usuarios e invitados.',
'Welcome 4'							=>	'Ver direcciones IP estáticas de los usuarios.',
'Welcome 5'							=>	'Suspender usuarios.',
'Welcome 6'							=>	'Censurar palabras.',
'Welcome 7'							=>	'Establecer promociones de grupos de usuario.',
'Welcome 8'							=>	'Purgar mensajes antiguos.',
'Welcome 9'							=>	'Gestionar reportes de mensajes.',
'About head'						=>	'Acerca de FluxBB',
'FluxBB version label'				=>	'Versión de FluxBB',
'Check for upgrade'					=>	'Comprobar actualizaciones',
'FluxBB version data'				=>	'v%s - %s',
'Server statistics label'			=>	'Estadísticas del servidor',
'View server statistics'			=>	'Ver estadísticas del servidor',
'Support label'						=>	'Soporte',
'Forum label'						=>	'Foro',
'IRC label'							=>	'Canal IRC',

// Language definitions used in admin_statistics.php
'PHPinfo disabled message'			=>	'La función de PHR phpinfo() ha sido deshabilitada en este servidor.',
'Server statistics head'			=>	'Estadísticas del servidor',
'Server load label'					=>	'Carga del servidor',
'Server load data'					=>	'%s - %s usuario(s) conectados',
'Environment label'					=>	'Entorno',
'Environment data OS'				=>	'Sistema operativo: %s',
'Show info'							=>	'Mostrar información',
'Environment data version'			=>	'PHP: %s - %s',
'Environment data acc'				=>	'Accelerator: %s',
'Turck MMCache'						=>	'Turck MMCache',
'Turck MMCache link'				=>	'turck-mmcache.sourceforge.net/',
'ionCube PHP Accelerator'			=>	'ionCube PHP Accelerator',
'ionCube PHP Accelerator link'		=>	'www.php-accelerator.co.uk/',
'Alternative PHP Cache (APC)'		=>	'Alternative PHP Cache (APC)',
'Alternative PHP Cache (APC) link'	=>	'www.php.net/apc/',
'Zend Optimizer'					=>	'Zend Optimizer',
'Zend Optimizer link'				=>	'www.zend.com/products/guard/zend-optimizer/',
'eAccelerator'						=>	'eAccelerator',
'eAccelerator link'					=>	'www.eaccelerator.net/',
'XCache'							=>	'XCache',
'XCache link'						=>	'xcache.lighttpd.net/',
'Database label'					=>	'Base de datos',
'Database data rows'				=>	'Filas: %s',
'Database data size'				=>	'Tamaño: %s',
);
