<?php

// Language definitions used in profile.php
$lang_profile = array(

// Navigation and sections
'Profile menu'					=>	'Menú de perfil',
'Section essentials'			=>	'Esenciales',
'Section personal'				=>	'Personal',
'Section messaging'				=>	'Mensajería',
'Section personality'			=>	'Personalidad',
'Section display'				=>	'Visualización',
'Section privacy'				=>	'Privacidad',
'Section admin'					=>	'Administración',

// Miscellaneous
'Username and pass legend'		=>	'Ingresa tu nombre de usuario y contraseña',
'Personal details legend'		=>	'Ingresa tus detalles personales',
'Contact details legend'		=>	'Ingresa tus detalles de mensajería',
'User activity'					=>	'Actividad del usuario',
'Paginate info'					=>	'Ingresa el número de temas y mensajes que deseas ver en cada página.',

// Password stuff
'Pass key bad'					=>	'El código de activación para contraseña es incorrecto, o ha expirado. Por favor solicita de nuevo una nueva contraseña. Si esto falla, contacta al administrador del foro en',
'Pass updated'					=>	'Tu contraseña se ha actualizado. Ahora puedes entrar con tu nueva contraseña.',
'Pass updated redirect'			=>	'Contraseña actualizada. Redirigiendo…',
'Wrong pass'					=>	'Antigua contraseña incorrecta',
'Change pass'					=>	'Cambiar contraseña',
'Change pass legend'			=>	'Ingresa y confirma tu nueva contraseña',
'Old pass'						=>	'Antigua contraseña',
'New pass'						=>	'Nueva contraseña',
'Confirm new pass'				=>	'Confirma tu nueva contraseña',
'Pass info'						=>	'Las contraseñas deben tener al menos 4 caracteres. Las contraseñas distinguen entre mayúsculas y minúsculas.',

// Email stuff
'Email key bad'					=>	'El código de activación de correo electrónico es incorrecto, o ha expirado. Por favor solicita de nuevo el cambio de dirección de correo electrónico. Si esto falla, contacta al administrador del foro en',
'Email updated'					=>	'Tu dirección de correo electrónico se ha actualizado.',
'Activate email sent'			=>	'Un correo electrónico se ha enviado a la dirección especificada, con instrucciones sobre cómo activar la nueva dirección de correo electrónico. Si no llega, puedes contactar al administrador del foro en',
'Email legend'					=>	'Ingresa tu nueva dirección de correo electrónico',
'Email instructions'			=>	'Un correo electrónico será enviado a tu nueva dirección, con un enlace de activación. Debes hacer clic en el enlace en el correo electrónico que recibas para activar tu nueva dirección.',
'Change email'					=>	'Cambiar dirección de correo electrónico',
'New email'						=>	'Nuevo correo electrónico',

// Avatar upload stuff
'Avatars disabled'				=>	'El administrador ha deshabilitado el soporte para avatares.',
'Too large ini'					=>	'El archivo seleccionad es demasiado grande para cargarse. El servidor no permitió la carga.',
'Partial upload'				=>	'El archivo seleccionado se cargó solo parcialmente. Por favor inténtalo de nuevo.',
'No tmp directory'				=>	'PHP no pudo guardar el archivo cargado en una ubicación temporal.',
'No file'						=>	'No seleccionaste un archivo para cargar.',
'Bad type'						=>	'El archivo que intentaste cargar no es de un tipo permitido. Los tipos permitidos son gif, jpeg y png.',
'Too wide or high'				=>	'El archivo que intentaste cargar es más ancho y/o alto que el máximo permitido',
'Too large'						=>	'El archivo que intentaste cargar es mayor máximo permitido',
'pixels'						=>	'pixeles',
'bytes'							=>	'bytes',
'Move failed'					=>	'El servidor no fue capaz de guardar el archivo cargado. Por favor contacta con el administrador del foro en',
'Unknown failure'				=>	'Ocurrió un error desconocido. Por favor inténtalo de nuevo.',
'Avatar upload redirect'		=>	'Avatar cargado. Redirigiendo…',
'Avatar deleted redirect'		=>	'Avatar eliminado. Redirigiendo…',
'Avatar desc'					=>	'Un avatar es una pequeña imagen que se mostrará bajo tu nombre de usuario en tus mensajes. No debe ser mayor a',
'Upload avatar'					=>	'Cargar avatar',
'Upload avatar legend'			=>	'Ingresa una imagen de avatar para cargar',
'Delete avatar'					=>	'Eliminar avatar', // only for admins
'File'							=>	'Archivo',
'Upload'						=>	'Cargar', // submit button

// Form validation stuff
'Forbidden title'				=>	'El título que ingresaste contiene una palabra prohibida. Debes elegir un título distinto.',
'Profile redirect'				=>	'Perfil actualizado. Redirigiendo…',

// Profile display stuff
'Users profile'					=>	'Perfil de %s',
'Username info'					=>	'Nombre de usuario: %s',
'Email info'					=>	'Correo electrónico: %s',
'Posts info'					=>	'Mensajes: %s',
'Registered info'				=>	'Registrado: %s',
'Last post info'				=>	'Último mensaje: %s',
'Last visit info'				=>	'Última visita: %s',
'Show posts'					=>	'Mostrar todos los mensajes',
'Show topics'					=>	'Mostrar todos los temas',
'Show subscriptions'			=>	'Mostrar todas las suscripciones',
'Realname'						=>	'Nombre real',
'Location'						=>	'Ubicación',
'Website'						=>	'Sitio Web',
'Invalid website URL'			=>	'La URL del sitio Web que ingresaste es inválida.',
'Website not allowed'			=>	'Aún no tienes permitido añadir un sitio Web a tu perfil.',
'Jabber'						=>	'Jabber',
'ICQ'							=>	'ICQ',
'MSN'							=>	'MSN Messenger',
'AOL IM'						=>	'AOL IM',
'Yahoo'							=>	'Yahoo! Messenger',
'Avatar'						=>	'Avatar',
'Signature'						=>	'Firma',
'Sig max size'					=>	'Longitud máxima: %s caracteres / Máxima cantidad de líneas: %s',
'Avatar legend'					=>	'Establece tus opciones de visualización de avatares',
'Avatar info'					=>	'Un avatar es una pequeña imagen que se mostrará bajo tu nombre de usuario en tus mensajes. Puedes cargar un avatar haciendo clic en el enlace siguiente.',
'Change avatar'					=>	'Cambiar avatar',
'Signature legend'				=>	'Redacta tu firma',
'Signature info'				=>	'Una firma es un pequeño texto que se adjunta a tus mensajes. En ella, puedes introducir casi cualquier cosa que desees. Tal vez te gustaría añadir tu cita favorita, o tu signo zodiacal. ¡Depende de ti! En tu firma puedes utilizar BBCode, si está permitido en este foro en particular. Puedes ver las funciones que están habilitadas/deshabilitadas listadas debajo, siempre que edites tu firma.',
'Sig preview'					=>	'Vista previa de la firma:',
'No sig'						=>	'No hay ninguna firma actualmente almacenada en tu perfil.',
'Signature quote/code/list/h'	=>	'Los siguientes BBCodes no están permitidos en las firmas: quote, code, list y heading.',
'Topics per page'				=>	'Temas',
'Posts per page'				=>	'Mensajes',
'Leave blank'					=>	'Dejar en blanco para usar la opción por defecto del foro.',
'Subscription legend'			=>	'Establece tus opciones de suscripción',
'Notify full'					=>	'Incluye una versión en texto simple de los nuevos mensajes en los correos electrónicos de notificación de suscripción.',
'Auto notify full'				=>	'Suscribirse automáticamente a cada tema en el cual publiques.',
'Show smilies'					=>	'Mostrar emoticonos como íconos gráficos.',
'Show images'					=>	'Mostrar imágenes en los mensajes.',
'Show images sigs'				=>	'Mostrar imágenes en las firmas de usuarios.',
'Show avatars'					=>	'Mostrar avatares de usuarios en los mensajes.',
'Show sigs'						=>	'Mostrar firmas de usuarios.',
'Style legend'					=>	'Selecciona tu estilo preferido',
'Styles'						=>	'Estilos',
'Admin note'					=>	'Nota del administrador',
'Pagination legend'				=>	'Introduce tus opciones de paginación',
'Post display legend'			=>	'Establece tus opciones de visualización de mensajes',
'Post display info'				=>	'Si tu conexión es lenta, deshabilita estas opciones. Particularmente mostrar imágenes en los mensajes y firmas hará que las páginas se carguen más rápido.',
'Instructions'					=>	'Cuando actualices tu perfil, serás redirigido de vuelta a esta página.',

// Administration stuff
'Group membership legend'		=>	'Elegir grupo de usuario',
'Save'							=>	'Guardar',
'Set mods legend'				=>	'Establecer acceso de moderador',
'Moderator in info'				=>	'Elige qué foros podrá moderar este usuario. Nota: esto solo aplica a los moderadores, los administradores siempre tendrán permisos completos en todos los foros.',
'Update forums'					=>	'Actualizar foros',
'Delete ban legend'				=>	'Eliminar (solo administradores) o suspender a un usuario',
'Delete user'					=>	'Eliminar usuario',
'Ban user'						=>	'Suspender usuario',
'Confirm delete legend'			=>	'Importante: leer antes de eliminar a un usuario',
'Confirm delete user'			=>	'Confirmar eliminación de usuario',
'Confirmation info'				=>	'Por favor confirma que deseas eliminar al usuario', // the username will be appended to this string
'Delete warning'				=>	'¡Advertencia! Los usuarios y/o mensajes eliminados no se pueden restaurar. Si decides no eliminar los mensajes realizados por este usuario, solo será posible eliminar dichos mensajes manualmente, más adelante.',
'Delete posts'					=>	'Eliminar cualquier mensaje y temas que haya realizado este usuario.',
'Delete'						=>	'Eliminar', // submit button (confirm user delete)
'User delete redirect'			=>	'Usuario eliminado. Redirigiendo…',
'Group membership redirect'		=>	'Membresía del grupo guardada. Redirigiendo…',
'Update forums redirect'		=>	'Permisos de moderador del foro actualizados. Redirigiendo…',
'Ban redirect'					=>	'Redirigiendo…',
'No delete admin message'		=>	'Los administradores no pueden ser eliminados. Para poder eliminar a este usuario, primero debes moverlo/a a un grupo de usuarios distinto.',

);
