<?php

// Language definitions used in both profile.php and register.php
$lang_prof_reg = array(

'Email legend'				=>	'Ingresa una dirección de correo electrónico válida',
'Email legend 2'			=>	'Ingresa y confirma una dirección de correo electrónico válida',
'Localisation legend'		=>	'Establece tus opciones de localización',
'Time zone'					=>	'Zona horaria',
'Time zone info'			=>	'Para que el foro muestre la hora correctamente, debes seleccionar tu zona horaria local. Si el horario de verano está en efecto, también debes marcar la opción que adelantará el reloj una hora.',
'DST'						=>	'El horario de verano está en efecto (adelanta el reloj una hora).',
'Time format'				=>	'Formato de hora',
'Date format'				=>	'Formato de fecha',
'Default'					=>	'Predeterminado',
'Language'					=>	'Idioma',
'Email setting info'		=>	'Elige si deseas que tu dirección de correo electrónico sea visible para otros usuario o no, y si deseas que otros usuarios te puedan enviar correos electrónicos por medio de foro (formulario de correo).',
'Email setting 1'			=>	'Mostrar tu dirección de correo electrónico.',
'Email setting 2'			=>	'Ocultar tu dirección de correo electrónico, pero permitir contacto a través de formulario.',
'Email setting 3'			=>	'Ocultar tu dirección de correo electrónico, y no permitir contacto a través de formulario.',
'Privacy options legend'	=>	'Establece tus opciones de privacidad',
'Confirm pass'				=>	'Confirmar contraseña',

'Username too short'		=>	'Los nombres de usuario deben tener una longitud de al menos 2 caracteres. Por favor elige otro nombre de usuario más largo.',
'Username too long'			=>	'Los nombres de usuario deben tener una longitud mayor a 25 caracteres. Por favor elige otro nombre de usuario más corto.',
'Username guest'			=>	'El nombre de usuario «guest» está reservado. Por favor elige otro nombre de usuario.',
'Username IP'				=>	'Los nombres de usuario no pueden ser como una dirección IP. Por favor elige otro nombre de usuario.',
'Username reserved chars'	=>	'Los nombres de usuario no pueden contener todos los caracteres \', " y [ o ] a la vez. Por favor elige otro nombre de usuario.',
'Username BBCode'			=>	'Los nombres de usuario no pueden contener ninguna de las etiquetas de formato de texto (BBCode) utilizadas por el foro. Por favor elige otro nombre de usuario.',
'Banned username'			=>	'El nombre de usuario que elegiste está suspendido en este foro. Por favor elige otro nombre de usuario.',
'Pass too short'			=>	'Las contraseñas deben tener una longitud de al menos 4 caracteres. Por favor elige otra contraseña más larga.',
'Pass not match'			=>	'Las contraseñas no coinciden.',
'Banned email'				=>	'La dirección de correo electrónico que ingresaste está suspendida en este foro. Por favor elige otra dirección de correo electrónico.',
'Dupe email'				=>	'Alguien ya se registró con esa dirección de correo electrónico. Por favor elige otra dirección de correo electrónico.',
'Sig too long'				=>	'Las firmas no pueden tener una longitud mayor a %1$s caracteres. Por favor elimina de tu firma %2$s caracteres.',
'Sig too many lines'		=>	'Las firmas no pueden tener más de %s líneas.',
'Bad ICQ'					=>	'Ingresaste un UIN de ICQ inválido. Por favor vuelve y corrígelo.',

'UTC-12:00'					=>	'(UTC-12:00) Línea internacional de cambio de fecha',
'UTC-11:00'					=>	'(UTC-11:00) Niue, Samoa Americana',
'UTC-10:00'					=>	'(UTC-10:00) Hawái, Islas Cook',
'UTC-09:30'					=>	'(UTC-09:30) Islas marquesas',
'UTC-09:00'					=>	'(UTC-09:00) Alaska, Islas Gambier',
'UTC-08:30'					=>	'(UTC-08:30) Islas Pitcairn',
'UTC-08:00'					=>	'(UTC-08:00) Pacífico',
'UTC-07:00'					=>	'(UTC-07:00) Montaña',
'UTC-06:00'					=>	'(UTC-06:00) Centro',
'UTC-05:00'					=>	'(UTC-05:00) Este',
'UTC-04:00'					=>	'(UTC-04:00) Atlántico',
'UTC-03:30'					=>	'(UTC-03:30) Terranova y Labrador',
'UTC-03:00'					=>	'(UTC-03:00) Amazonas, Groenlandia Central',
'UTC-02:00'					=>	'(UTC-02:00) Atlántico',
'UTC-01:00'					=>	'(UTC-01:00) Islas Azores, Cabo Verde, Groenladia Oriental',
'UTC'						=>	'(UTC) Europa Occidental, Greenwich',
'UTC+01:00'					=>	'(UTC+01:00) Europa central, África Occidental',
'UTC+02:00'					=>	'(UTC+02:00) Europa del este, África Central',
'UTC+03:00'					=>	'(UTC+03:00) África Oriental',
'UTC+03:30'					=>	'(UTC+03:30) Irán',
'UTC+04:00'					=>	'(UTC+04:00) Moscú, Samara',
'UTC+04:30'					=>	'(UTC+04:30) Afganistán',
'UTC+05:00'					=>	'(UTC+05:00) Pakistán',
'UTC+05:30'					=>	'(UTC+05:30) India, Sri Lanka',
'UTC+05:45'					=>	'(UTC+05:45) Nepal',
'UTC+06:00'					=>	'(UTC+06:00) Bangladesh, Bután, Ekaterimburgo',
'UTC+06:30'					=>	'(UTC+06:30) Islas Cocos, Myanmar',
'UTC+07:00'					=>	'(UTC+07:00) Indochina, Novosibirsk',
'UTC+08:00'					=>	'(UTC+08:00) China, Australia Occidental, Krasnoyarsk',
'UTC+08:45'					=>	'(UTC+08:45) Australia Occidental',
'UTC+09:00'					=>	'(UTC+09:00) Japón, Corea, Palaos, Irkutsk',
'UTC+09:30'					=>	'(UTC+09:30) Australia Meridional',
'UTC+10:00'					=>	'(UTC+10:00) Australia',
'UTC+10:30'					=>	'(UTC+10:30) Islas Lord Howe',
'UTC+11:00'					=>	'(UTC+11:00) Islas Salomón, Micronesia, Vanuatu',
'UTC+11:30'					=>	'(UTC+11:30) Isla Norfolk',
'UTC+12:00'					=>	'(UTC+12:00) Nueva Zelanda, Fiyi, Magadan',
'UTC+12:45'					=>	'(UTC+12:45) Islas Chatham',
'UTC+13:00'					=>	'(UTC+13:00) Tonga, Islas Phoenix, Kamchatka',
'UTC+14:00'					=>	'(UTC+14:00) Islas de la línea'

);
