<?php

// Language definitions used in search.php
$lang_search = array(

// The search form
'User search'						=>	'Búsqueda de usuarios',
'No search permission'				=>	'No tienes permiso para usar la función de búsqueda.',
'Search flood'						=>	'Deben pasar al menos %s segundos entre búsquedas. Por favor espera %s segundos e inténtalo de nuevo.',
'Search'							=>	'Buscar',
'Search criteria legend'			=>	'Introduce tu criterio de búsqueda',
'Search info'						=>	'Para buscar por palabra clave, ingresa un término o términos para buscar. Separa los términos con espacios. Utiliza AND, OR y NOT para refinar tu búsqueda. Para buscar por autor, ingresa el nombre de usuario del autor cuyos mensajes deseas buscar. Utiliza el carácter comodín (*) para coincidencias parciales.',
'Keyword search'					=>	'Buscar por palabra clave',
'Author search'						=>	'Buscar por autor',
'Search in legend'					=>	'Selecciona dónde buscar',
'Search in info'					=>	'Elige en qué foro deseas buscar, y si quieres buscar en temas del foro, mensajes, o ambos.',
'Search multiple forums info'		=>	'Si no hay foros seleccionados se buscara en todos.',
'Forum search'						=>	'Foro',
'All forums'						=>	'Todos los foros',
'Search in'							=>	'Buscar en',
'Message and subject'				=>	'Texto del mensaje y asunto del mensaje',
'Message only'						=>	'Texto del mensaje únicamente',
'Topic only'						=>	'Asunto del mensaje únicamente',
'Sort by'							=>	'Ordenar por',
'Sort order'						=>	'Orden',
'Search results legend'				=>	'Selecciona cómo ver los resultados',
'Search results info'				=>	'Puedes elegir cómo deseas ordenar y mostrar los resultados.',
'Sort by post time'					=>	'Fecha de publicación',
'Sort by author'					=>	'Autor',
'Sort by subject'					=>	'Asunto',
'Sort by forum'						=>	'Foro',
'Ascending'							=>	'Ascendente',
'Descending'						=>	'Descendente',
'Show as'							=>	'Mostrar resultados como',
'Show as topics'					=>	'Temas',
'Show as posts'						=>	'Mensajes',

// Results
'Search'							=>	'Búsqueda',
'Search results'					=>	'Resultados de búsqueda',
'Quick search show_new'				=>	'Nuevos',
'Quick search show_recent'			=>	'Activos',
'Quick search show_unanswered'		=>	'Sin respuesta',
'Quick search show_replies'			=>	'Publicados',
'Quick search show_user_topics'		=>	'Temas de %s',
'Quick search show_user_posts'		=>	'Mensajes de %s',
'Quick search show_subscriptions'	=>	'Suscritos por %s',
'By keywords show as topics'		=>	'Temas con mensajes que contienen \'%s\'',
'By keywords show as posts'			=>	'Mensajes que contienen \'%s\'',
'By user show as topics'			=>	'Temas con mensajes de %s',
'By user show as posts'				=>	'Mensajes de %s',
'By both show as topics'			=>	'Temas con mensajes que contienen \'%s\', de %s',
'By both show as posts'				=>	'Mensajes que contienen \'%s\', de %s',
'No terms'							=>	'Deben ingresar al menos una palabra clave y/o un autor para buscar.',
'No hits'							=>	'Tu búsqueda no tuvo resultados.',
'No user posts'						=>	'No hay mensajes de este usuario en este foro.',
'No user topics'					=>	'No hay temas de este usuario en este foro.',
'No subscriptions'					=>	'Este usuario no está actualmente suscrito a ningún tema.',
'No new posts'						=>	'No hay temas con nuevos mensajes desde tu última visita.',
'No recent posts'					=>	'No se han hecho nuevos mensajes en las últimas 24 horas.',
'No unanswered'						=>	'No hay mensajes sin respuesta en este foro.',
'Go to post'						=>	'Ir al mensaje',
'Go to topic'						=>	'Ir al tema'

);
